[package]
name = "crator"
version = "1.0.1"
authors = ["Montasir Mirghani <montasir@webio.tech>"]
edition = "2024"
description = "High-performance Rust toolkit for HTTP/HTTPS requests, JSON processing, and environment management."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dr-montasir/crator"
repository = "https://github.com/dr-montasir/crator"
readme = "README.md"
keywords = ["http", "json", "crates", "env", "rust"]
categories = ["development-tools", "web-programming::http-client", "parsing", "value-formatting", "api-bindings"]
exclude = [
    ".github/**",
    "examples/**",
    "tests/**",
    "Cargo.lock",
    "dev.md"
]

[dependencies]
dotenvy = "0.15.7"
native-tls = "0.2.18"

[lib]
name = "crator"
path = "src/lib.rs"
